#!/bin/sh
set -e -x

trap exit TERM INT

update_symlinks_for_nft ()
(
    cd /sbin
    find . -type l | 
        while IFS= read -r f; do 
            filename="$(basename "$f")"
            linked_to="$(basename "$(readlink "$filename")")"
            if [ "$linked_to" = "xtables-legacy-multi" ]; then
                ln -sf "xtables-nft-multi" "$filename"
            fi
        done
)

test -d /sys/module/iptable_nat || update_symlinks_for_nft

for src_range in ${SRC_RANGES}; do
    if echo ${src_range} | grep -Eq ":"; then
        ip6tables -t filter -I FORWARD -s ${src_range} -p ${DEST_PROTO} --dport ${SRC_PORT} -j ACCEPT
    else
        iptables -t filter -I FORWARD -s ${src_range} -p ${DEST_PROTO} --dport ${SRC_PORT} -j ACCEPT
    fi
done

for dest_ip in ${DEST_IPS}; do
    if echo ${dest_ip} | grep -Eq ":"; then
        [ $(cat /proc/sys/net/ipv6/conf/all/forwarding) == 1 ] || exit 1
        ip6tables -t filter -A FORWARD -d ${dest_ip}/128 -p ${DEST_PROTO} --dport ${DEST_PORT} -j DROP
        ip6tables -t nat -I PREROUTING ! -s ${dest_ip}/128 -p ${DEST_PROTO} --dport ${SRC_PORT} -j DNAT --to [${dest_ip}]:${DEST_PORT}
        ip6tables -t nat -I POSTROUTING -d ${dest_ip}/128 -p ${DEST_PROTO} -j MASQUERADE
    else
        [ $(cat /proc/sys/net/ipv4/ip_forward) == 1 ] || exit 1
        iptables -t filter -A FORWARD -d ${dest_ip}/32 -p ${DEST_PROTO} --dport ${DEST_PORT} -j DROP
        iptables -t nat -I PREROUTING ! -s ${dest_ip}/32 -p ${DEST_PROTO} --dport ${SRC_PORT} -j DNAT --to ${dest_ip}:${DEST_PORT}
        iptables -t nat -I POSTROUTING -d ${dest_ip}/32 -p ${DEST_PROTO} -j MASQUERADE
    fi
done

if [ ! -e /pause ]; then
    mkfifo /pause
fi
</pause
